import serverConfig from "./serverConfig"

const apiRoutes = {
    "AssociationsURL": `${serverConfig.apiAddress}/api/association`,
    "AssociationTypesURL": `${serverConfig.apiAddress}/api/association_type`,
    "DocumentURL" : `${serverConfig.apiAddress}/api/document`,
    "StorageURL":`${serverConfig.apiAddress}`,
    "ProjectsURL": `${serverConfig.apiAddress}/api/project`,
    "InProgressProjectsURL": `${serverConfig.apiAddress}/api/project/inProgress`,
    "ProjectAddPartenaireURL": `${serverConfig.apiAddress}/api/project/add/partner`,
    "ProjectRemovePartenaireURL": `${serverConfig.apiAddress}/api/project/remove/partner`,
    "ProjectChangeStatusURL": `${serverConfig.apiAddress}/api/project/changeStatus`,
    "AssociationProjectsURL": `${serverConfig.apiAddress}/api/project/association`,
    "AssociationMembersURL": `${serverConfig.apiAddress}/api/association/member`,
    "ActivateAssociationMember": `${serverConfig.apiAddress}`,
    "PartenairesURL": `${serverConfig.apiAddress}/api/partner`,
    "CategoriesURL" : `${serverConfig.apiAddress}/api/category`,
    "UsersURL": `${serverConfig.apiAddress}/api/user`,
    "UsersPaginationURL": `${serverConfig.apiAddress}/api/user/taille`,
    "RolesURL": `${serverConfig.apiAddress}/api/role`,
    "LoginURL": `${serverConfig.apiAddress}/api/auth/login`,
    "LogoutURL": `${serverConfig.apiAddress}/api/auth/logout`,
    "RegisterURL": `${serverConfig.apiAddress}/api/auth/register`,
    "AddMemberAssociationURL": `${serverConfig.apiAddress}/api/member/association/add`,
    "RemoveMemberAssociationURL": `${serverConfig.apiAddress}/api/member/association/remove`,
    "ConnectedUserURL" : `${serverConfig.apiAddress}/api/auth/me`,
    "ResetPasswordInit" : `${serverConfig.apiAddress}/api/auth/resetpasswordinit`,
    "ResetPasswordProcess" : `${serverConfig.apiAddress}/api/auth/resetpasswordprocess`,
    "VerifyTwoFactorCode" : `${serverConfig.apiAddress}/api/auth/verify`,
    "VerifyTokenURL" : `${serverConfig.apiAddress}/api/auth/verify`,
    "ResendTwoFactorCode" : `${serverConfig.apiAddress}/api/auth/verify/resend`,
    "RefreshTokenURL" : `${serverConfig.apiAddress}/api/auth/refresh`,
    "AccessTokenURL": `${serverConfig.apiAddress}/api/payment/mp/init`,
    "InitPaymentURL": `${serverConfig.apiAddress}/api/payment/mp/process`,
    "getAllPaymentByProject": `${serverConfig.apiAddress}/api/payment/contributionByproject`,
    'ActivateMember': `${serverConfig.apiAddress}/api/member/association/activate`,
    "GetProjectStat": `${serverConfig.apiAddress}/api/stat/project`,
    "GetAssociationInactiveMembers": `${serverConfig.apiAddress}/api/association/inactive-member`,
    "StatContributions" : `${serverConfig.apiAddress}/api/stat/contributions`,
    "ExportAssociationMembers": `${serverConfig.apiAddress}/api/export/members`,
    "ExportContributionsByProject": `${serverConfig.apiAddress}/api/export/contribution`,
    "SendNotification": `${serverConfig.apiAddress}/api/sms/send`,
    "RegisterPartnerURL": `${serverConfig.apiAddress}/api/auth/register-partner`,
    "LoginPartnerURL": `${serverConfig.apiAddress}/api/auth/login-partner`,
    "LogoutPartnerURL": `${serverConfig.apiAddress}/api/auth/logout-partner`,
}

export default apiRoutes;