const AssociationTypes = {
    CURRENT_ASSOCIATION_PENDING : "CURRENT_ASSOCIATION_PENDING",
    CURRENT_ASSOCIATION_SUCCESS : "CURRENT_ASSOCIATION_SUCCESS",
    CURRENT_ASSOCIATION_ERROR : "CURRENT_ASSOCIATION_ERROR",
}

export default AssociationTypes;