const AuthTypes = {
    USER_LOGIN_PENDING : "USER_LOGIN_PENDING",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_ERROR : "USER_LOGIN_ERROR",

    USER_LOGOUT_PENDING : "USER_LOGOUT_PENDING",
    USER_LOGOUT_SUCCESS : "USER_LOGOUT_SUCCESS",
    USER_LOGOUT_ERROR : "USER_LOGOUT_ERROR",

    USER_REGISTER_PENDING : "USER_REGISTER_PENDING",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
    USER_REGISTER_ERROR : "USER_REGISTER_ERROR",
}

export default AuthTypes;