export const GET_BLOG_PENDING = 'GET_BLOG_PENDING';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_ERROR = 'GET_BLOG_ERROR';
export const GET_BLOG_RESET = 'GET_BLOG_RESET';

export const GET_ALL_BLOG_PENDING = 'GET_ALL_BLOG_PENDING';
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS';
export const GET_ALL_BLOG_ERROR = 'GET_ALL_BLOG_ERROR';
export const GET_ALL_BLOG_RESET = 'GET_ALL_BLOG_RESET';

export const POST_BLOG_PENDING = 'POST_BLOG_PENDING';
export const POST_BLOG_SUCCESS = 'POST_BLOG_SUCCESS';
export const POST_BLOG_ERROR = 'POST_BLOG_ERROR';
export const POST_BLOG_RESET = 'POST_BLOG_RESET';
