export const GET_CATEGORY_PENDING = 'GET_CATEGORY_PENDING';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
export const GET_CATEGORY_RESET = 'GET_CATEGORY_RESET';

export const CREATE_CATEGORY_PENDING = 'CREATE_CATEGORY_PENDING';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';
export const CREATE_CATEGORY_RESET = 'CREATE_CATEGORY_RESET';

export const MODIFY_CATEGORY_PENDING = 'MODIFY_CATEGORY_PENDING';
export const MODIFY_CATEGORY_SUCCESS = 'MODIFY_CATEGORY_SUCCESS';
export const MODIFY_CATEGORY_ERROR = 'MODIFY_CATEGORY_ERROR';
export const MODIFY_CATEGORY_RESET = 'MODIFY_CATEGORY_RESET';
