export const POST_COMMENT_PENDING = 'POST_COMMENT_PENDING';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR';
export const POST_COMMENT_RESET = 'POST_COMMENT_RESET';