export const GET_ALL_DOMAINE_PENDING = 'GET_ALL_DOMAINE_PENDING';
export const GET_ALL_DOMAINE_SUCCESS = 'GET_ALL_DOMAINE_SUCCESS';
export const GET_ALL_DOMAINE_ERROR = 'GET_ALL_DOMAINE_ERROR';
export const GET_ALL_DOMAINE_RESET = 'GET_ALL_DOMAINE_RESET';

export const GET_DOMAINE_BY_POST_PENDING = 'GET_DOMAINE_BY_POST_PENDING';
export const GET_DOMAINE_BY_POST_SUCCESS = 'GET_DOMAINE_BY_POST_SUCCESS';
export const GET_DOMAINE_BY_POST_ERROR = 'GET_DOMAINE_BY_POST_ERROR';
export const GET_DOMAINE_BY_POST_RESET = 'GET_DOMAINE_BY_POST_RESET';

export const CREATE_THEMATIQUE_PENDING = 'CREATE_THEMATIQUE_PENDING';
export const CREATE_THEMATIQUE_SUCCESS = 'CREATE_THEMATIQUE_SUCCESS';
export const CREATE_THEMATIQUE_ERROR = 'CREATE_THEMATIQUE_ERROR';
export const CREATE_THEMATIQUE_RESET = 'CREATE_THEMATIQUE_RESET';

export const MODIFY_THEMATIQUE_PENDING = 'MODIFY_THEMATIQUE_PENDING';
export const MODIFY_THEMATIQUE_SUCCESS = 'MODIFY_THEMATIQUE_SUCCESS';
export const MODIFY_THEMATIQUE_ERROR = 'MODIFY_THEMATIQUE_ERROR';
export const MODIFY_THEMATIQUE_RESET = 'MODIFY_THEMATIQUE_RESET';

