export const POST_FAQ_PENDING = 'POST_FAQ_PENDING';
export const POST_FAQ_SUCCESS = 'POST_FAQ_SUCCESS';
export const POST_FAQ_ERROR = 'POST_FAQ_ERROR';
export const POST_FAQ_RESET = 'POST_FAQ_RESET';

export const GET_ALL_FAQ_PENDING = 'GET_ALL_FAQ_PENDING';
export const GET_ALL_FAQ_SUCCESS = 'GET_ALL_FAQ_SUCCESS';
export const GET_ALL_FAQ_ERROR = 'GET_ALL_FAQ_ERROR';
export const GET_ALL_FAQ_RESET = 'GET_ALL_FAQ_RESET';
