export const POST_GLOSSARY_PENDING = 'POST_GLOSSARY_PENDING';
export const POST_GLOSSARY_SUCCESS = 'POST_GLOSSARY_SUCCESS';
export const POST_GLOSSARY_ERROR = 'POST_GLOSSARY_ERROR';
export const POST_GLOSSARY_RESET = 'POST_GLOSSARY_RESET';

export const GET_ALL_GLOSSARY_PENDING = 'GET_ALL_GLOSSARY_PENDING';
export const GET_ALL_GLOSSARY_SUCCESS = 'GET_ALL_GLOSSARY_SUCCESS';
export const GET_ALL_GLOSSARY_ERROR = 'GET_ALL_GLOSSARY_ERROR';
export const GET_ALL_GLOSSARY_RESET = 'GET_ALL_GLOSSARY_RESET';
