export const UPLOAD_IMAGE_PENDING = 'UPLOAD_IMAGE_PENDING';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_ERROR = 'UPLOAD_IMAGE_ERROR';
export const UPLOAD_IMAGE_RESET = 'UPLOAD_IMAGE_RESET';