export const GET_JOB_OFFER_PENDING = 'GET_JOB_OFFER_PENDING';
export const GET_JOB_OFFER_SUCCESS = 'GET_JOB_OFFER_SUCCESS';
export const GET_JOB_OFFER_ERROR = 'GET_JOB_OFFER_ERROR';
export const GET_JOB_OFFER_RESET = 'GET_JOB_OFFER_RESET';

export const POST_JOB_OFFER_PENDING = 'POST_JOB_OFFER_PENDING';
export const POST_JOB_OFFER_SUCCESS = 'POST_JOB_OFFER_SUCCESS';
export const POST_JOB_OFFER_ERROR = 'POST_JOB_OFFER_ERROR';
export const POST_JOB_OFFER_RESET = 'POST_JOB_OFFER_RESET';
