export const GET_ALL_POST_PENDING = 'GET_ALL_POST_PENDING';
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
export const GET_ALL_POST_ERROR = 'GET_ALL_POST_ERROR';
export const GET_ALL_POST_RESET = 'GET_ALL_POST_RESET';

export const GET_ALL_POST_BY_DOMAIN_PENDING = 'GET_ALL_POST_BY_DOMAIN_PENDING';
export const GET_ALL_POST_BY_DOMAIN_SUCCESS = 'GET_ALL_POST_BY_DOMAIN_SUCCESS';
export const GET_ALL_POST_BY_DOMAIN_ERROR = 'GET_ALL_POST_BY_DOMAIN_ERROR';
export const GET_ALL_POST_BY_DOMAIN_RESET = 'GET_ALL_POST_BY_DOMAIN_RESET';

export const GET_ALL_POST_BY_CATEGORY_PENDING = 'GET_ALL_POST_BY_CATEGORY_PENDING';
export const GET_ALL_POST_BY_CATEGORY_SUCCESS = 'GET_ALL_POST_BY_CATEGORY_SUCCESS';
export const GET_ALL_POST_BY_CATEGORY_ERROR = 'GET_ALL_POST_BY_CATEGORY_ERROR';
export const GET_ALL_POST_BY_CATEGORY_RESET = 'GET_ALL_POST_BY_CATEGORY_RESET';

export const ADD_NEW_POST_PENDING = 'ADD_NEW_POST_PENDING';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_ERROR = 'ADD_NEW_POST_ERROR';
export const ADD_NEW_POST_RESET = 'ADD_NEW_POST_RESET';

export const ADD_NEW_TRANSACTION_PENDING = 'ADD_NEW_TRANSACTION_PENDING';
export const ADD_NEW_TRANSACTION_SUCCESS = 'ADD_NEW_TRANSACTION_SUCCESS';
export const ADD_NEW_TRANSACTION_ERROR = 'ADD_NEW_TRANSACTION_ERROR';
export const ADD_NEW_TRANSACTION_RESET = 'ADD_NEW_TRANSACTION_RESET';

export const GET_POST_BY_ID_PENDING = 'GET_POST_BY_ID_PENDING';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_ERROR = 'GET_POST_BY_ID_ERROR';
export const GET_POST_BY_ID_RESET = 'GET_POST_BY_ID_RESET';

export const GET_ALL_POST_FEATURED_PENDING = 'GET_ALL_POST_FEATURED_PENDING';
export const GET_ALL_POST_FEATURED_SUCCESS = 'GET_ALL_POST_FEATURED_SUCCESS';
export const GET_ALL_POST_FEATURED_ERROR = 'GET_ALL_POST_FEATURED_ERROR';
export const GET_ALL_POST_FEATURED_RESET = 'GET_ALL_POST_FEATURED_RESET';

export const GET_ALL_POST_RH_PENDING = 'GET_ALL_POST_RH_PENDING';
export const GET_ALL_POST_RH_SUCCESS = 'GET_ALL_POST_RH_SUCCESS';
export const GET_ALL_POST_RH_ERROR = 'GET_ALL_POST_RH_ERROR';
export const GET_ALL_POST_RH_RESET = 'GET_ALL_POST_RH_RESET';

export const GET_ALL_POST_POPULAR_PENDING = 'GET_ALL_POST_POPULAR_PENDING';
export const GET_ALL_POST_POPULAR_SUCCESS = 'GET_ALL_POST_POPULAR_SUCCESS';
export const GET_ALL_POST_POPULAR_ERROR = 'GET_ALL_POST_POPULAR_ERROR';
export const GET_ALL_POST_POPULAR_RESET = 'GET_ALL_POST_POPULAR_RESET';

export const MODIFY_POST_PENDING = 'MODIFY_POST_PENDING';
export const MODIFY_POST_SUCCESS = 'MODIFY_POST_SUCCESS';
export const MODIFY_POST_ERROR = 'MODIFY_POST_ERROR';
export const MODIFY_POST_RESET = 'MODIFY_POST_RESET';


export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_RESET = 'DELETE_POST_RESET';

