export const POST_TESTIMONIAL_PENDING = 'POST_TESTIMONIAL_PENDING';
export const POST_TESTIMONIAL_SUCCESS = 'POST_TESTIMONIAL_SUCCESS';
export const POST_TESTIMONIAL_ERROR = 'POST_TESTIMONIAL_ERROR';
export const POST_TESTIMONIAL_RESET = 'POST_TESTIMONIAL_RESET';

export const GET_ALL_TESTIMONIAL_PENDING = 'GET_ALL_TESTIMONIAL_PENDING';
export const GET_ALL_TESTIMONIAL_SUCCESS = 'GET_ALL_TESTIMONIAL_SUCCESS';
export const GET_ALL_TESTIMONIAL_ERROR = 'GET_ALL_TESTIMONIAL_ERROR';
export const GET_ALL_TESTIMONIAL_RESET = 'GET_ALL_TESTIMONIAL_RESET';
