export const GET_PUBLICATION_ADMIN_TO_VALIDATE_PENDING = 'GET_PUBLICATION_ADMIN_TO_VALIDATE_PENDING';
export const GET_PUBLICATION_ADMIN_TO_VALIDATE_SUCCESS = 'GET_PUBLICATION_ADMIN_TO_VALIDATE_SUCCESS';
export const GET_PUBLICATION_ADMIN_TO_VALIDATE_ERROR = 'GET_PUBLICATION_ADMIN_TO_VALIDATE_ERROR';
export const GET_PUBLICATION_ADMIN_TO_VALIDATE_RESET = 'GET_PUBLICATION_ADMIN_TO_VALIDATE_RESET';

export const GET_USER_NOTIFICATION_PENDING = 'GET_USER_NOTIFICATION_PENDING';
export const GET_USER_NOTIFICATION_SUCCESS = 'GET_USER_NOTIFICATION_SUCCESS';
export const GET_USER_NOTIFICATION_ERROR = 'GET_USER_NOTIFICATION_ERROR';
export const GET_USER_NOTIFICATION_RESET = 'GET_USER_NOTIFICATION_RESET';


export const VALIDATE_PUBLICATION_PENDING = 'VALIDATE_PUBLICATION_PENDING';
export const VALIDATE_PUBLICATION_SUCCESS = 'VALIDATE_PUBLICATION_SUCCESS';
export const VALIDATE_PUBLICATION_ERROR = 'VALIDATE_PUBLICATION_ERROR';
export const VALIDATE_PUBLICATION_RESET = 'VALIDATE_PUBLICATION_RESET';
